# プロジェクト設定ファイル
# Project Configuration File

project:
  name: "プロジェクト名"
  created_date: "2025-06-01"

user:
  name: "ユーザー名"

settings:
  default_language: "ja"
  timezone: "Asia/Tokyo"
  document_format: "markdown"

# メタデータテンプレート用設定
metadata_defaults:
  author: "${user.name}"